<!doctype html>
<html class="no-js" lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Java异常</title>
    <meta name="description" content="Java异常">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="http://dashidan.com/apple-touch-icon.png">
    <link rel="stylesheet" href="http://dashidan.com/css/bootstrap.css">
    <link rel="stylesheet" href="http://dashidan.com/css/dashidan.css">
</head>
<body>
<!--[if lte IE 9]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade
    your browser</a> to improve your experience and security.</p>
<![endif]-->

<nav class="navbar navbar-default">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">
                <img src="http://dashidan.com/img/dsd24.png">
            </a>
            <a class="navbar-brand" href="http://dashidan.com/index.html">大屎蛋教程网</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="http://dashidan.com/about.html">关于</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <!-- 顶部面包屑导航-->
    <ol class="breadcrumb">
        <li><a href="http://dashidan.com/index.html"><b>首页</b></a></li>
        <li><a href="http://dashidan.com/article/java/index.html"><b>Java教程</b></a></li>
        <li class="active"><a
            href="http://dashidan.com/article/java/basic/index.html"><b>教程列表</b></a></li>
    </ol>
    <hr>
    <!-- 顶部标签页-->
    <ul class="nav nav-tabs" role="tablist">
        <li class="active"><a href="http://dashidan.com/article/java/basic/index.html">教程列表</a></li>
        <li><a href="http://dashidan.com/article/java/addenda/index.html">附录</a></li>
    </ul>
    <!--文档区-->
    <div>
        <!-- 替换这个区域-->
        <div class="list-group"><a class="list-group-item list-group-item-warning" href="#15."><h3>15. Java异常</h3></a><a
            class="list-group-item" href="#1."> ▶ 1. Java异常机制相关关键字</a><a class="list-group-item" href="#2."> ▶ 2.
            Java异常框架</a><a class="list-group-item" href="#3."> ▶ 3. 捕获异常</a><a class="list-group-item" href="#4."> ▶ 4.
            抛出异常</a><a class="list-group-item" href="#5."> ▶ 5. finally关键字</a><a class="list-group-item" href="#6."> ▶
            6. 自定义异常</a><a class="list-group-item" href="#7."> ▶ 7. 示例代码</a><a class="list-group-item" href="#8."> ▶ 8.
            相关文章</a></div>
        <div class="jumbotron">
            <p>Java异常是Java提供的一种识别及响应错误的一致性机制.
            </p>
        </div>
        <a href="#top" id="1."><b>1. Java异常机制相关关键字🔝</b></a>
        <p>Java异常机制相关关键字有:
            <code>try</code>、<code>catch</code>、<code>finally</code>、<code>throw</code>、<code>throws</code>.
            关键字解释: </p>
        <ul>
            <li>try 用于监听. 将被监听的代码(可能抛出异常的代码)放在try语句块之内, 当try语句块内发生异常时,异常就被抛出.</li>
            <li>catch 用来捕获try语句块中发生的异常.</li>
            <li>finally finally语句块总是会被执行. 主要用于回收在<code>try</code>块里打开的物理资源(如文件, 网络连接, 数据库连接等).</li>
        </ul>
        <div class="bs-callout bs-callout-warning">
            <h4>finally语句中return</h4>
            <p>只有finally块执行完成之后,才会执行try或者catch块中的return或者throw语句. 如果finally中使用了return或者throw等终止方法的语句,则就不会跳回执行,直接停止.
            </p>
        </div>
        <ul>
            <li>throw 用于抛出异常.</li>
            <li>throws 用在方法签名中,用于声明该方法可能抛出的异常.</li>
        </ul>
        <a href="#top" id="2."><b>2. Java异常框架🔝</b></a>
        <p>Java将可抛出(Throwable)的结构分为三种类型：</p>
        <ul>
            <li>编译异常(Checked Exception)</li>
            <li>运行时异常(RuntimeException)</li>
            <li>错误(Error)</li>
        </ul>
        <p>Java异常框架继承关系如图:
            <img class="center-block img-responsive" src="http://dashidan.com/img/java/basic/15-1.jpg" alt="图15-1"/></p>
        <h3>1.Throwable</h3>
        <p><code>Throwable</code>是<code>Java</code>语言中所有错误或异常的超类, 包含两个子类:<code>Error</code>和<code>Exception</code>.它们通常用于指示发生了异常情况.<code>Throwable</code>包含了其线程创建时线程执行堆栈的快照,提供了<code>printStackTrace()</code>等接口用于获取堆栈跟踪数据等信息.
        </p>
        <h3>2.运行时异常RuntimeException</h3>
        <p><code>RuntimeException</code>是那些可能在<code>Java</code>虚拟机正常运行期间抛出的异常的超类, 简称<code>运行时异常</code>.
            RuntimeException及其子类都被称为运行时异常.</p>
        <p>Java编译器不会检查运行时异常.当程序中可能出现这类异常时,倘若既"没有通过throws声明抛出它",也"没有用try-catch语句捕获它",还是会编译通过.</p>
        <p>虽然Java编译器不会检查运行时异常, 但是我们也可以通过throws进行声明抛出, 也可以通过try-catch对它进行捕获处理. 如果产生运行时异常,则需要通过修改代码来进行避免.</p>
        <p>例如： </p>
        <ul>
            <li>除数为零时产生的ArithmeticException异常</li>
            <li>数组越界时产生的IndexOutOfBoundsException异常</li>
            <li>fail-fail机制产生的ConcurrentModificationException异常等,都属于运行时异常.</li>
        </ul>
        <table class="table table-bordered table-responsive">
            <caption>部分常用运行时异常说明</caption>
            <thead>
            <tr class="success">
                <td>异常</td>
                <td>描述</td>
            </tr>
            </thead>
            <tbody>
            <tr class="active">
                <td>ArithmeticException</td>
                <td>除数为零异常</td>
            </tr>
            <tr>
                <td>ArrayIndexOutOfBoundsException</td>
                <td>数组越界</td>
            </tr>
            <tr class="active">
                <td>ClassCastException</td>
                <td>对象转型错误</td>
            </tr>
            <tr>
                <td>IllegalArgumentException</td>
                <td>参数不合法</td>
            </tr>
            <tr class="active">
                <td>IndexOutOfBoundsException</td>
                <td>指示某排序索引(例如对数组、字符串或向量的排序)超出范围</td>
            </tr>
            <tr>
                <td>NegativeArraySizeException</td>
                <td>数组长度为负值</td>
            </tr>
            <tr class="active">
                <td>NullPointerException</td>
                <td>空指针异常</td>
            </tr>
            <tr>
                <td>NumberFormatException</td>
                <td>当应用程序试图将字符串转换成一种数值类型,但该字符串不能转换为适当格式时,抛出该异常.</td>
            </tr>
            </tbody>
        </table>
        <h3>3.编译异常Exception</h3>
        <p><code>Exception</code>类以及<code>Exception</code>的子类中除了"运行时异常"之外的其它子类都属于被检查异常.
            此类异常,要么通过throws进行声明抛出,要么通过try-catch进行捕获处理,否则不能通过编译.</p>
        <table class="table table-bordered table-responsive">
            <caption>部分常用编译异常说明</caption>
            <thead>
            <tr class="success">
                <td>异常</td>
                <td>描述</td>
            </tr>
            </thead>
            <tbody>
            <tr class="active">
                <td>ClassNotFoundException</td>
                <td>应用程序试图加载类时,找不到相应的类,抛出该异常.</td>
            </tr>
            <tr>
                <td>FileNotFoundException</td>
                <td>文件不存在异常</td>
            </tr>
            <tr class="active">
                <td>ClassCastException</td>
                <td>对象转型错误</td>
            </tr>
            <tr>
                <td>InterruptedException</td>
                <td>一个线程被另一个线程中断,抛出该异常.</td>
            </tr>
            <tr class="active">
                <td>NoSuchFieldException</td>
                <td>请求的变量不存在</td>
            </tr>
            <tr>
                <td>NoSuchMethodException</td>
                <td>请求的方法不存在</td>
            </tr>
            </tbody>
        </table>
        <h3>4.Error</h3>
        <p><code>Error</code>类及其子类统称<code>错误</code>. 用于指示试图捕获的严重问题, 大多数这样的错误都是异常条件. 和<code>运行时异常</code>一样,
            编译器也不会检查<code>Error</code>. 当资源不足、约束失败、或是其它导致程序无法继续运行的条件发生时, 就产生错误. 程序本身无法修复这些错误.</p>
        <p>例: </p>
        <ul>
            <li>VirtualMachineError就属于错误.</li>
        </ul>
        <div class="bs-callout bs-callout-danger">
            <h4>按照Java惯例, 不应该实现任何新的Error子类, 需要自定义异常可以采用Exception类.
            </h4>
        </div>
        <div class="bs-callout bs-callout-success">
            <h4>到底该哪一种异常?</h4>
            <p>对于可以恢复的条件使用被检查异常,对于程序错误使用运行时异常.虚拟机及系统错误采用Error.
            </p>
        </div>
        <a href="#top" id="3."><b>3. 捕获异常🔝</b></a>
        <p>使用<code>try</code>和<code>catch</code>关键字可以捕获异常.<code>try/catch</code>代码块放在异常可能发生的地方. </p>
        <p>语法如下：</p>
        <pre class="prettyprint"><code class="java language-java">try {
    /** 程序代码*/
} catch (Exception e) {
    /** 异常处理*/
}
</code></pre>
        <p>一个<code>try</code>代码块后面跟随多个<code>catch</code>代码块的情况就叫多重捕获. 可以在 try 语句后面添加任意数量的 catch 块.
            如果保护代码中发生异常,异常被抛给第一个 catch 块. 如果抛出异常的数据类型与捕获异常类型匹配, 就会被捕获.
            如果不匹配,它会被传递给下一个<code>catch</code>块.直到异常被捕获或者通过所有的<code>catch</code>块.</p>
        <p>语法如下：</p>
        <pre class="prettyprint"><code class="java language-java">try {
    /** 程序代码*/
} catch (Exception1 e) {
    /** 异常处理*/
} catch (Exception1 e) {
    /** 异常处理*/
}
</code></pre>
        <a href="#top" id="4."><b>4. 抛出异常🔝</b></a>
        <p>可以使用<code>throw</code>关键字抛出一个异常.</p>
        <pre class="prettyprint"><code class="java language-java">public static void testThrow() {
    /** 方法体*/
    throw new NullPointerException();
}
</code></pre>
        <p>如果一个方法没有捕获一个<code>编译异常</code>, 那么该方法必须使用<code>throws</code>关键字来声明. <code>throws</code>关键字放在方法签名的尾部.</p>
        <p>示例代码:</p>
        <pre class="prettyprint"><code class="java language-java">public static void testThrows() throws NullPointerException {
    /** 方法体*/
}
</code></pre>
        <p>一个方法可以声明抛出多个异常,多个异常之间用逗号隔开.</p>
        <p>例如,下面的方法声明抛出<code>NullPointerException</code>和<code>ArithmeticException</code></p>
        <p>示例代码:</p>
        <pre class="prettyprint"><code class="java language-java">public static void testThrows() throws NullPointerException, ArithmeticException {
    /** 方法体*/
}
</code></pre>
        <a href="#top" id="5."><b>5. finally关键字🔝</b></a>
        <p><code>finally</code>关键字用来创建在<code>try</code>代码块后面执行的代码块. 无论是否发生异常,<code>finally</code>代码块中的代码总会被执行. 在<code>finally</code>代码块中,可以运关闭链接,
            释放系统资源等必须要执行的语句. </p>
        <p><code>finally</code>代码块出现在<code>catch</code>代码块最后. </p>
        <p>语法如下：</p>
        <pre class="prettyprint"><code class="java language-java">try {
    /** 方法体*/
} catch (Exception e) {
    /** 异常处理*/
} finally {
    /** finally语句*/
}
</code></pre>
        <div class="bs-callout bs-callout-warning">
            <h4>finally 块并非强制添加.</h4>
            <p>try 代码后不能既没 catch 块也没 finally 块.</p>
        </div>
        <p>示例代码:</p>
        <pre class="prettyprint"><code class="java language-java">package com.dashidan.lesson15;

/**
 * 大屎蛋教程网-dashidan.com
 * &lt;p&gt;
 * Java教程基础篇: 15.Java异常
 * 测试finally return
 */
public class Demo2 {
    public static void main(String[] args) {
        int result = testFinallyReturn();
        System.out.println("result: " + result);
    }

    public static int testFinallyReturn() {
        int a;
        try {
            a = 1;
            /** 抛出异常*/
            System.out.println("抛出异常");
            throw new NullPointerException();
        } catch (NullPointerException e) {
            a = 2;
            /** 捕获异常*/
            System.out.println("捕获异常");
            e.printStackTrace();
            /** 注意这里没有返回*/
            System.out.println("注意这里没有返回");
            return a;
        } finally {
            a = 3;
            System.out.println("finally执行返回");
            /** 抛出异常后, 执行finally的语句, 如果这里返回，不再执行catch中语句*/
            return a;
        }
    }
}
</code></pre>
        <p>输出:</p>
        <pre><code>抛出异常
捕获异常
注意这里没有返回
finally执行返回
result: 3
java.lang.NullPointerException
    at com.dashidan.basic.lession15.Demo2.testFinallyReturn(Demo2.java:21)
    at com.dashidan.basic.lession15.Demo2.main(Demo2.java:11)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
</code></pre>
        <a href="#top" id="6."><b>6. 自定义异常🔝</b></a>
        <p>在<code>Java</code>中自定义异常需要注意:</p>
        <ul>
            <li>所有异常都必须是 Throwable 的子类.</li>
            <li>如果想写一个检查性异常类,则需要继承 Exception 类.</li>
            <li>如果想写一个运行时异常类,那么需要继承 RuntimeException 类.</li>
        </ul>
        <pre class="prettyprint"><code class="java language-java">package com.dashidan.lesson15;

/**
 * 大屎蛋教程网-dashidan.com
 * &lt;p&gt;
 * Java教程基础篇: 15.Java异常
 * 自定义异常
 */
public class SelfException extends Exception {
}
</code></pre>
        <a href="#top" id="7."><b>7. 示例代码🔝</b></a>
        <pre class="prettyprint"><code class="java language-java">package com.dashidan.lesson15;

/**
 * 大屎蛋教程网-dashidan.com
 * &lt;p&gt;
 * Java教程基础篇: 15.Java异常
 */
public class Demo1 {
    public static void main(String[] args) {
        try {
            /** 方法体*/
            testThrow();
            testThrows();
        } catch (NullPointerException e) {
            /** 异常处理*/
            System.out.println("run catch NullPointerException.");
            e.printStackTrace();
        } catch (Exception e) {
            /** 异常处理*/
            System.out.println("run catch Exception.");
            e.printStackTrace();
        } finally {
            /** finally语句*/
            System.out.println("run finally.");
        }
    }

    public static void testThrow() {
        /** 方法体*/
        throw new NullPointerException();
    }

    public static void testThrows() throws NullPointerException, ArithmeticException {
        /** 方法体*/
    }
}
</code></pre>
        <p>输出:</p>
        <pre><code>java.lang.NullPointerException
at com.dashidan.basic.lession15.Demo1.testThrow(Demo1.java:30)
at com.dashidan.basic.lession15.Demo1.main(Demo1.java:12)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
run catch NullPointerException.
run finally.
</code></pre>
        <a href="#top" id="8."><b>8. 相关文章🔝</b></a>
        <ul>
            <li><a href="http://dashidan.com/article/java/addenda/Java示例代码使用方法.html">Java示例代码使用方法</a></li>
        </ul>
    </div>
    <hr>
    <!-- 底部面包屑导航-->
    <ol class="breadcrumb">
        <li><a href="http://dashidan.com/index.html"><b>首页</b></a></li>
        <li><a href="http://dashidan.com/article/java/index.html"><b>Java教程</b></a></li>
        <li class="active"><a
            href="http://dashidan.com/article/java/basic/index.html"><b>教程列表</b></a></li>
    </ol>
    <hr>
    <!--<nav>-->
    <div class="text-center">
        <div>
            <a href="http://dashidan.com/article/java/basic/Java集合类.html">🔺 上一篇: Java集合类</a>
        </div>
        <div>
            <a href="http://dashidan.com/article/java/basic/Java位运算.html">🔻 下一篇: Java位运算</a>
        </div>
    </div>
    <!--</nav>-->
</div>

<div style="display:none;">
    <script src="https://s19.cnzz.com/z_stat.php?id=1264355070&web_id=1264355070" language="JavaScript"></script>
</div>

<script src="http://dashidan.com/js/jquery-3.2.1.min.js"></script>
<script src="http://dashidan.com/js/vendor/modernizr-custom.js"></script>
<script src="http://dashidan.com/js/bootstrap.js"></script>
<script src="http://dashidan.com/js/google-code-prettify/run_prettify.js"></script>
</body>
</html>
